### ISSUE TITLE
Support for filters in ModelAdmin

### ISSUE THREAD

**Issue by rddesmond** [elton2048/wagtail-orderable#13]
Thank you for making this plugin, it's super useful!

I was looking to use filters in the ModelAdmin view, this is not supported.  The problem is that the query parameter that is generated and used is the absolute position in the list (which would depend on what which remains after filtering).

A proposed PR is #12 . This passes the pk for object to move before (when moving up the list) or after (when moving down the list) and adjusts the sort_order based on that.

**Comment by elton2048** [comment]
Merge #12 should support for filters. Thanks for contribution!
