### ISSUE TITLE
Issue with Duplicate Sort_Order Values

### ISSUE THREAD

**Issue by rddesmond** [elton2048/wagtail-orderable#17]
Thank you for this package!

I was testing further yesterday and noticed that there was an issue with duplicate sort_order ids (it gets weird).  I created #16 to resolve it.  This:

- Adds a function to remove duplicate (the sort order is re if duplicates are found)
- Fixes case that produced them (new items are added with MAX instead of COUNT, because deletes cause gaps)
- Updates the UI to cancel the move and show an error if the ajax command doesn't return 200.
- Handles sort_order with 0 correctly

**Comment by elton2048** [comment]
Fixed by #16 and included in `1.0.2`
