### ISSUE TITLE
Error in README

### ISSUE THREAD

**Issue by ryanbagwell** [elton2048/wagtail-orderable#2]
Great app. Minor documentation issue. OrderableMixin should come before ModelAdmin, like:

```
class YourModelAdmin(OrderableMixin, ModelAdmin):
    model = YourModel
```

**Comment by elton2048** [comment]
Thanks for that! I don't even know that issue before. Great to know that.

For anyone interest the issue there is a reference about that: https://www.ianlewis.org/en/mixins-and-python
