### ISSUE TITLE
Missing static files in pypi package

### ISSUE THREAD

**Issue by ryanbagwell** [elton2048/wagtail-orderable#3]
Probably need to add a MANIFEST.in file or something.

Again, great app. Thanks!

**Comment by fabienheureux** [comment]
Hi, I don't know if this is related, but it seems to be. 
After installing this package through pipenv (pypi), the `collectstatic` command was not able to find any static files. 
Really great app though, saved me a few hours and headaches. 
Thanks !

**Comment by djdmorrison** [comment]
Should be solved as part of PR #5

**Comment by elton2048** [comment]
#5 includes MANIFEST.in to include static files.
