### ISSUE TITLE
Support for Django 4

### ISSUE THREAD

**Issue by urlsangel** [elton2048/wagtail-orderable#36]
Hi Elton

I've just upgraded a Wagtail app that uses this package to Django 4, and am getting this error:

```
from wagtailorderable.modeladmin.mixins import OrderableMixin
File "/usr/local/lib/python3.10/site-packages/wagtailorderable/modeladmin/mixins.py", line 1, in <module>
from django.conf.urls import url
ImportError: cannot import name 'url' from 'django.conf.urls' (/usr/local/lib/python3.10/site-packages/django/conf/urls/__init__.py)
```

This looks like a simple fix, swapping out `url` for `re_path`, any chance this could be updated and released?

https://stackoverflow.com/a/70319607

Thanks,

Russell.

**Comment by elton2048** [comment]
This should be fixed via #35 and the new version(1.1.0) rolled out has already included that. Please report again if any issue still exist.
