### ISSUE TITLE
New Release on PyPi

### ISSUE THREAD

**Issue by fericsepi** [elton2048/wagtail-orderable#9]
As per comment in #5 - could you make a new release please?

**Comment by fericsepi** [comment]
Thanks. There's a new release available now with the fix in #5.
wagtail-orderable 1.0.1
https://pypi.org/project/wagtail-orderable/

**Comment by fericsepi** [comment]
Reopened as 1.0.1 release is broken - please look at #15

**Comment by elton2048** [comment]
Should release 1.0.2, please comment the issue if any problem.
